### ISSUE TITLE
Unexpected Application Error! Failed to fetch

### ISSUE THREAD

**Issue by wvaughn409** [code4recovery/oiaa-direct#1]
after running npm install and making the additional changes suggested in the readme, I proceeded to execute npm run dev. Vite tells me to access the local site at :
http://localhost:5173/
Accessing this site in Edge or Firefox results in errors all over the page:
![image](https://github.com/code4recovery/oiaa-direct/assets/9452611/16eb7bcd-0c93-4d61-9604-19c5cf19efb5)
...but I saw the readme advises to disable CORS, so I did some reading online and saw that Chromium-based browsers make this easy to do, so I tracked down my chrome.exe, opened that path in an Administrator command prompt, and ran it like this:

$ chrome.exe --disable-web-security --user-data-dir=C:\deleteme

..which resulted in a good demo page:
![image](https://github.com/code4recovery/oiaa-direct/assets/9452611/0762defa-b5dd-4149-8660-475fcf5c4e87)

Just thought it would be good to open this issue and mark it closed, in case you would like to add the additional steps involving chromium runtime flags to the readme. Hope that helps! :)

**Comment by tim-rohrer** [comment]
Thanks. Since the approach for disabling CORS varies by browser and platform, and this is a (hopefully) temporary issue while we work on initial development, I'll hold off on updating the docs.

Are you interested in contributing to the code for this repo?

**Comment by wvaughn409** [comment]
Yes absolutely!!! 💯
